
CREATE TABLE Ecom_Banners(
	Id int  NOT NULL,
	PID int NULL,
	ImgPath varchar(255) NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL
) 

CREATE TABLE Ecom_Brands(
	Id int  NOT NULL,
	PID int NULL,
	Brand varchar(255) NULL,
	Brand_BN varchar(255) NULL,
	ImgPath varchar(255) NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL
)
CREATE TABLE Ecom_Carts(
	TOId int  NOT NULL,
	CID int NULL,
	PID int NULL,
	TONumber varchar(255) NULL,
	PName varchar(255) NULL,
	HostAddress varchar(255) NULL,
	UnitPrice int NULL,
	NetPrice int NULL
)
CREATE TABLE Ecom_Customers(
	Id int  NOT NULL,
	CID varchar(255) NULL,
	TONumber varchar(255) NULL,
	Name varchar(255) NULL,
	Address varchar(255) NULL,
	Area varchar(255) NULL,
	MobileNo varchar(255) NULL,
	PhoneNo varchar(255) NULL,
	Email varchar(255) NULL,
	Username varchar(255) NULL,
	Password varchar(255) NULL,
	Priority varchar(255) NULL,
	HostAddress varchar(255) NULL,
	FileUrl varchar(255) NULL,
	FileExtension varchar(255) NULL,
	FileImage varchar(255) NULL,
	Birthday datetime NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	UpdateBy varchar(255) NULL,
	UpdateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
	Counted int NULL
) 
CREATE TABLE Ecom_Features(
	Id int  NOT NULL,
	PID int NULL,
	PName varchar(255) NULL,
	PName_BN varchar(255) NULL,
	Brand varchar(255) NULL,
	Brand_BN varchar(255) NULL,
	Description varchar(255) NULL,
	Description_BN varchar(255) NULL,
	ImgPath varchar(255) NULL,
	UnitPrice float NULL,
	OfferPrice float NULL,
	UnitsInStock int NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL
)
CREATE TABLE Ecom_Menu(
	MenuId int  NOT NULL,
	Title varchar(50) NOT NULL,
	IsActive bit NULL,
	Path varchar(250) NULL,
	DisplayOrder int NULL,
	ParentId int NULL,
	CreatedUser varchar(100) NULL,
	ModifiedUser varchar(100) NULL,
	CreatedDate datetime NULL,
	ModifiedDate datetime NULL,
	SystemInfo varchar(50) NULL,
	Parameter varchar(50) NULL,
	NodeId varchar(50) NULL,
	Style varchar(50) NULL,
 )
CREATE TABLE Ecom_MenuRoles(
	MenuRoleId int  NOT NULL,
	MenuId int NOT NULL,
	RoleId int NULL,
	CreatedUser varchar(100) NULL,
	ModifiedUser varchar(100) NULL,
	CreatedDate datetime NULL,
	ModifiedDate datetime NULL,
	SystemInfo varchar(50) NULL,
 )
CREATE TABLE Ecom_Menus(
	Id int  NOT NULL,
	MenuId int NULL,
	Title int NULL,
	Path int NULL,
	ParentId int NULL,
	DisplayOrder int NULL,
	Parameter int NULL,
	NodeId int NULL,
	Style int NULL,
	Categories int NULL,
	MenuRoles int NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	UpdateBy varchar(255) NULL,
	UpdateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
)
CREATE TABLE Ecom_Offers(
	CId int  NOT NULL,
	CName varchar(255) NULL,
	CName_BN varchar(255) NULL,
	CouponNo varchar(255) NULL,
	ValidFrom datetime NULL,
	ValidTo datetime NULL,
	ValidCountry varchar(255) NULL,
	ValidOutletName varchar(255) NULL,
	DiscountPrice int NULL,
	Percent bit NULL,
	Reason varchar(255) NULL,
	Active bit NULL
)
CREATE TABLE Ecom_OrderDetails(
	Id int  NOT NULL,
	OrderId int NULL,
	TONumber varchar(255) NULL,
	PID int NULL,
	PName varchar(255) NULL,
	PQty int NULL,
	ItemQty int NULL,
	UnitPrice int NULL,
	NetPrice int NULL,
	ImgPath varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	UpdateBy varchar(255) NULL,
	UpdateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
)
CREATE TABLE Ecom_Orders(
	Id int  NOT NULL,
	OID int NULL,
	TONumber varchar(255) NULL,
	CustomerId int NULL,
	CouponId int NULL,
	PaymentId int NULL,
	Discount int NULL,
	Reason varchar(255) NULL,
	TotalItemQty int NULL,
	DeliveryCharge int NULL,
	TotalPrice int NULL,
	NetPrice int NULL,
	Address varchar(255) NULL,
	Area varchar(255) NULL,
	DeliveryTime varchar(255) NULL,
	OrderStatus int NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL
) 
CREATE TABLE Ecom_ProductIamges(
	id int  NOT NULL,
	pid int NULL,
	image varchar(500) NULL,
	default_image int NULL,
)
CREATE TABLE Ecom_Products(
	Id int  NOT NULL,
	PID  AS (Id),
	PName varchar(255) NULL,
	PName_BN varchar(255) NULL,
	Brand varchar(255) NULL,
	Brand_BN varchar(255) NULL,
	Discount float NULL,
	MRP float NULL,
	UnitPrice float NULL,
	Unit float NULL,
	UnitsInStock int NULL,
	Category varchar(255) NULL,
	Category_BN varchar(255) NULL,
	Description varchar(255) NULL,
	Description_BN varchar(255) NULL,
	SID int NULL,
	Rol varchar(255) NULL,
	ParentId int NULL,
	ImgPath varchar(255) NULL,
	Inserted_By varchar(255) NULL,
	Inserted_Date datetime NULL,
	Display varchar(255) NULL,
	FileUrl varchar(255) NULL,
	FileExtension varchar(255) NULL,
	FileImage varchar(255) NULL,
	RankId int NULL,
	route varchar(50) NULL,
	iconName varchar(50) NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
 )
CREATE TABLE Ecom_Roles(
	RoleId int  NOT NULL,
	RoleName varchar(256) NULL,
	RoleDescription varchar(256) NULL,
	IsActive bit NULL,
	CreatedUser varchar(100) NULL,
	ModifiedUser varchar(100) NULL,
	CreatedDate datetime NULL,
	ModifiedDate datetime NULL,
	SystemInfo varchar(50) NULL,
	DepartmentId int NULL,
	KeyResponsibilities varchar(max) NULL,
	EducationQualification varchar(max) NULL,
 )
CREATE TABLE Ecom_ServiceMan(
	ID int  NOT NULL,
	Name varchar(50) NOT NULL,
	Phone varchar(50) NOT NULL,
	Email varchar(50) NULL,
	Address1 varchar(50) NULL,
	Address2 varchar(50) NULL,
	ContactPerson varchar(50) NULL,
	status int NULL,
 )
CREATE TABLE Ecom_Settings(
	Id int  NOT NULL,
	GID int NULL,
	GText varchar(255) NULL,
	Code varchar(255) NULL,
	Text varchar(max) NULL,
	ImgPath varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	UpdateBy varchar(255) NULL,
	UpdateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL
) 
CREATE TABLE Ecom_ShoppingCartData(
	TempOrderID int  NOT NULL,
	PID int NOT NULL,
	PName varchar(50) NOT NULL,
	UnitPrice money NOT NULL,
	Quantity int NOT NULL,
	hostaddress varchar(2000) NULL,
 )
CREATE TABLE Ecom_Suppliers(
	ID int  NOT NULL,
	Name varchar(50) NOT NULL,
	Phone varchar(50) NOT NULL,
	Email varchar(50) NULL,
	Address1 varchar(50) NULL,
	Address2 varchar(50) NULL,
	ContactPerson varchar(50) NULL,
	status int NULL,
 )
CREATE TABLE Ecom_Tasks(
	Id int  NOT NULL,
	TID int NULL,
	Title varchar(255) NULL,
	Description varchar(max) NULL,
	Date datetime NULL,
	Time_from varchar(255) NULL,
	Time_to varchar(255) NULL,
	Location varchar(max) NULL,
	Notify int NULL,
	Email varchar(max) NULL,
	Priority int NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
)
CREATE TABLE Ecom_user_informations(
	Id int  NOT NULL,
	UID int NULL,
	Name varchar(255) NULL,
	Email varchar(255) NULL,
	Username varchar(255) NULL,
	Password varchar(255) NULL,
	FileUrl varchar(255) NULL,
	FileExtension varchar(255) NULL,
	FileImage varchar(255) NULL,
	Birthday datetime NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
)
CREATE TABLE Ecom_Users(
	Id int  NOT NULL,
	roleid int NULL,
	Name varchar(255) NULL,
	Email varchar(255) NULL,
	Username varchar(255) NULL,
	Password varchar(255) NULL,
	Phone varchar(255) NULL,
	FileExtension varchar(255) NULL,
	FileImage varchar(255) NULL,
	Birthday datetime NULL,
	TrackedId varchar(255) NULL,
	CreateBy varchar(255) NULL,
	CreateDate datetime NULL,
	IsDelete bit NULL,
	Active bit NULL,
)
